backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "team"
    folder: "src/content/team"
    create: false
    delete: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "Type", widget: "hidden", default: "team" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Description", name: "Description", widget: "markdown" }
      - { label: "Image", name: "Image", widget: "image", required: true }
      - { label: "Email", name: "Email", widget: "string", required: true }
      - { label: "Phone", name: "Phone", widget: "string", required: true }

  - name: "about"
    label: "about"
    folder: "src/content/about"
    create: false
    delete: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "Type", widget: "hidden", default: "about" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Header", name: "title", widget: "string" }
      - { label: "Description", name: "Description", widget: "markdown" }

  - name: "listing"
    label: "listing"
    folder: "src/content/listing"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "Type", widget: "hidden", default: "listing" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Property Type"
        name: "PropertyType"
        widget: "select"
        options: ["commercial", "retail", "office", "industrial", "hotel"]

      - label: "Listing Type"
        name: "ListingType"
        widget: "select"
        options: ["sale", "lease"]
      - { label: "Brochure", name: "Brochure", widget: "file" }
      - { label: "Location", name: "Loacation", widget: "string" }
      - { label: "Maps Src", name: "Map", widget: "string" }
      - { label: "Size", name: "Size", widget: "string" }
      - { label: "Price", name: "Price", widget: "string" }
      - label: "Images"
        name: "Images"
        widget: "list"
        field: { label: Image, name: Image, widget: image }
      - { label: "Description", name: "Description", widget: "markdown" }
      - label: Highlights
        name: Highlights
        widget: "list"
        fields:
          - { label: Description, name: Description, widget: string }
      - label: Specs
        name: Specs
        widget: "list"
        fields:
          - { label: Key, name: Key, widget: string }
          - { label: Value, name: Value, widget: string }
      - label: Areas
        name: Areas
        widget: "list"
        fields:
          - { label: Area, name: Area, widget: string }
          - { label: Size, name: Size, widget: string }
