backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "team"
    folder: "src/content/team"
    create: false
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "Type", widget: "hidden", default: "team" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "Name", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "Description",
          widget: "markdown",
          required: true,
        }
      - { label: "Image", name: "Image", widget: "image", required: true }
      - { label: "Email", name: "Email", widget: "string", required: true }
      - { label: "Phone", name: "Phone", widget: "string", required: true }

  - name: "about"
    label: "about"
    folder: "src/content/about"
    create: false
    delete: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "Type", widget: "hidden", default: "about" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "Header", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "Description",
          widget: "markdown",
          required: false,
          default: "",
        }

  - name: "listing"
    label: "listing"
    folder: "src/content/listing"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "Type", widget: "hidden", default: "listing" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string", required: true }

      - label: "Agent"
        name: "Agent"
        widget: "select"
        options: ["Gurjant Gill", "Paul Gill"]
        required: true

      - label: "Property Type"
        name: "PropertyType"
        widget: "select"
        options:
          [
            "Commercial",
            "Retail",
            "Office",
            "Industrial",
            "Hotel",
            "Land",
            "Business",
          ]
        required: true

      - label: "Listing Type"
        name: "ListingType"
        widget: "select"
        options: ["Sale", "Lease", "Sale or Lease"]
        required: true
      - { label: "Brochure", name: "Brochure", widget: "file", required: false }
      - {
          label: "Location",
          name: "Loacation",
          widget: "string",
          required: false,
        }
      - { label: "Maps Src", name: "Map", widget: "string", required: false }
      - { label: "Size", name: "Size", widget: "string", required: false }
      - { label: "Price", name: "Price", widget: "string", required: false }
      - label: "Images"
        name: "Images"
        widget: "list"
        required: false
        field: { label: Image, name: Image, widget: image }
      - { label: "Header", name: "Header", widget: "string", required: true }
      - {
          label: "Description",
          name: "Description",
          widget: "markdown",
          required: false,
        }
      - label: Highlights
        name: Highlights
        widget: "list"
        required: false
        fields:
          - { label: Description, name: Description, widget: string }
      - label: Specs
        name: Specs
        widget: "list"
        required: false
        fields:
          - { label: Key, name: Key, widget: string }
          - { label: Value, name: Value, widget: string }
      - label: Areas
        name: Areas
        widget: "list"
        required: false
        fields:
          - { label: Area, name: Area, widget: string }
          - { label: Size, name: Size, widget: string }//
 - name: "reslisting"
    label: "residential listing"
    folder: "src/content/reslisting"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Type", name: "Type", widget: "hidden", default: "reslisting" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string", required: true }

      - label: "Agent"
        name: "Agent"
        widget: "select"
        options: ["Gurjant Gill", "Paul Gill",]
        required: true

      - label: "Listing Type"
        name: "ListingType"
        widget: "select"
        options: ["Sale", "Lease", "Sale or Lease"]
        required: true
      - { label: "Brochure", name: "Brochure", widget: "file", required: false }
      - {
          label: "Location",
          name: "Loacation",
          widget: "string",
          required: false,
        }
      - { label: "Maps Src", name: "Map", widget: "string", required: false }
      - { label: "Size", name: "Size", widget: "string", required: false }
      - { label: "Price", name: "Price", widget: "string", required: false }
      - { label: "Matterport", name: "Matterport", widget: "string", required: false }
      - label: "Images"
        name: "Images"
        widget: "list"
        required: false
        field: { label: Image, name: Image, widget: image }
      - { label: "Header", name: "Header", widget: "string", required: true }
      - {
          label: "Description",
          name: "Description",
          widget: "markdown",
          required: false,
        }



